# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./chronos.h
SOURCES += ./main.cpp \
    ./chronos.cpp
