# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../KnxCommon/common.h \
    ../QtKnxModule/gidt_module.h \
    ../QtKnxCore/ModuleDB.h \
    ./pstn.h \
    ./w2cUSBM_API.h
SOURCES += ../KnxCommon/common.cpp \
    ../QtKnxModule/gidt_module.cpp \
    ./main.cpp \
    ../QtKnxCore/ModuleDB.cpp \
    ./pstn.cpp
