# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./qtknxdesigner.h
SOURCES += ./main.cpp \
    ./qtknxdesigner.cpp
FORMS += ./qtknxdesigner.ui
RESOURCES += ./qtknxdesigner.qrc
