# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../KnxCommon/common.h \
    ../QtKnxModule/gidt_module.h \
    ./gsm.h \
    ./main.h
SOURCES += ../KnxCommon/common.cpp \
    ../QtKnxModule/gidt_module.cpp \
    ./gsm.cpp \
    ./main.cpp
