# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../KnxCommon/common.h \
    ./gidt_module.h
SOURCES += ../KnxCommon/common.cpp \
    ./gidt_module.cpp \
    ./main.cpp
