# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../KnxCommon/common.h \
    ../QtKnxModule/gidt_module.h \
    ./pdxalarm.h \
    ./XSocket.h
SOURCES += ../KnxCommon/common.cpp \
    ../QtKnxModule/gidt_module.cpp \
    ./main.cpp \
    ./pdxalarm.cpp \
    ./XSocket.cpp
